import type {Metadata} from "next"
import {Noto_Sans_Myanmar} from "next/font/google"
import "./globals.css"
import Layout from "@/components/Layout"

const mmfont = Noto_Sans_Myanmar({subsets: ["myanmar"], weight: "500"})

export const metadata: Metadata = {
    title: "မြန်မာစကားပုံများ",
    description: "Generated by create next app",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/book.png" type="image/png" />
            </head>
            <body className={mmfont.className}>
                <Layout>{children}</Layout>
            </body>
        </html>
    )
}
